ALG: CROSSQ
EXP_NAME: crossq

PIXEL_BASED: True
NATIVE_DOWNSCALING: True

LEARNING_RATE: 0.0003
GAMMA: 0.99
BATCH_SIZE: 64 
BUFFER_SIZE: 50000
LEARNING_STARTS: 20000
TRAIN_FREQUENCY: 4
GRADIENT_STEPS: 16 
BATCHNORM_MOMENTUM: 0.99

AUTOTUNE: True
TARGET_ENTROPY_SCALE: 0.89
ALPHA: 0.2


SCAN_STEPS: 1000
NUM_ENVS: 16 
TOTAL_TIMESTEPS: 10000000
